name = "quaterni"
version = "1.0.1"
description = "Pure Gleam quaternion math library for 3D rotations"
licences = ["MIT"]
repository = { type = "github", user = "renatillas", repo = "quaterni" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_community_maths = ">= 2.0.0 and < 3.0.0"
vec = ">= 3.0.1 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
